boards/de10_nano/board_specific_top.sv, boards/de2_115/board_specific_top.sv
Перенес исправления для решения проблемы с яркостью HEX на DE2-115.
Переписал привязку rst на DE2-115 и DE10-Nano. Оба key на DE10-Nano запараллелил с S1-S2 платы с tm1638.
=> HEX, reset DE2-115 и DE10-Nano

boards/zybo_z7/board_specific.tcl, boards/zybo_z7/board_specific.xdc, boards/zybo_z7/board_specific_top.sv, scripts/steps/00_setup.source_bash, scripts/steps/00_setup_xilinx.source_bash
Added basic support for `zybo_z7` and edit the `vivado_install_dir` variable.
=> Added basic support for zybo_z7

boards/de10_nano/board_specific_top.sv, boards/de1_soc/board_specific.qsf, boards/de1_soc/board_specific.sdc, boards/de1_soc/board_specific_top.sv, boards/de2_115/board_specific.sdc, boards/de2_115/board_specific_top.sv, labs/common/tm1638_board.sv
TM1638: auto clock divider.
DE1-SoC: VGA added. DE1-SoC, DE2-115: altera board projects unification.
DE10-Nano: mic, tm1638 pins optimization.
=> TM1638 improving. DE1-SoC, DE2-115 unification. DE10-Nano optimization.

boards/ice40hx8k_evb_yosys/Makefile, boards/ice40hx8k_evb_yosys/board_specific.pcf, boards/ice40hx8k_evb_yosys/board_specific_top.sv, clean_all.bash, scripts/steps/00_setup.source_bash, scripts/steps/00_setup_yosys.source_bash, scripts/steps/01_clean_all.source_bash, scripts/steps/03_synthesize_for_fpga.source_bash, scripts/steps/04_configure_fpga.source_bash, scripts/steps/05_run_gui_for_fpga_synthesis.source_bash
I've added basic Yosys support. Currenlty iCE40HX8K-EVB is the only board supported.
There following issues were discovered:
- multidimantional arrays with more than two dims are not supported. I.e. ```wire [1:0][1:0][1:0] name``` will trigger syntax error.
- ```break``` statement in a loop is not supported.
- some labs have multiple ```top```, why ?
- power operator ```**``` gets translated into internal ```$pow``` cell which is not present in iCE40. Fixed it by using shift.
- zero dimantion is also not supported, always triggers error.
=> Added support for Yosys toolchain

labs/02_mux/top.sv
=> 02_mux Yosys fix

boards/ice40hx8k_evb_yosys/board_specific_top.sv, boards/orangecrab_ecp5_yosys/Makefile, boards/orangecrab_ecp5_yosys/board_specific_top.sv, scripts/steps/00_setup_yosys.source_bash
- Three upload methods implemented: ecpprog, openFPGALoader and dfu-util (for OrangeCrab only).
- Fixed a number of issues with GPIO assignment, etc.
=> Ecp5 yosys

boards/ice40hx8k_evb_yosys/board_specific_top.sv, labs/11_2_note_recognition_with_filtering/01_clean.bash, labs/11_2_note_recognition_with_filtering/02_simulate_rtl.bash, labs/11_2_note_recognition_with_filtering/03_synthesize_for_fpga.bash, labs/11_2_note_recognition_with_filtering/04_configure_fpga.bash, labs/11_2_note_recognition_with_filtering/05_run_gui_for_fpga_synthesis.bash, labs/11_2_note_recognition_with_filtering/06_choose_another_fpga_board.bash, labs/11_2_note_recognition_with_filtering/07_synthesize_for_asic.bash, labs/11_2_note_recognition_with_filtering/08_visualize_asic_synthesis_results_1.bash, labs/11_2_note_recognition_with_filtering/09_visualize_asic_synthesis_results_2.bash, labs/11_2_note_recognition_with_filtering/top.sv, labs/11_3_mic_to_uart/01_clean.bash, labs/11_3_mic_to_uart/02_simulate_rtl.bash, labs/11_3_mic_to_uart/03_synthesize_for_fpga.bash, labs/11_3_mic_to_uart/04_configure_fpga.bash, labs/11_3_mic_to_uart/05_run_gui_for_fpga_synthesis.bash, labs/11_3_mic_to_uart/06_choose_another_fpga_board.bash, labs/11_3_mic_to_uart/07_synthesize_for_asic.bash, labs/11_3_mic_to_uart/08_visualize_asic_synthesis_results_1.bash, labs/11_3_mic_to_uart/09_visualize_asic_synthesis_results_2.bash, labs/11_3_mic_to_uart/hex2wav.pl, labs/11_3_mic_to_uart/top.sv, labs/common/inmp441_mic_i2s_receiver.sv, labs/common/inmp441_mic_i2s_receiver_v2.sv, labs/common/uart_transmitter.sv
1. Added my imeplementation for INMP441 I2S module: takes into account clk_mhz, generates ready strobe, allows setting sampling rate.
2. Added my implementation of UART transmitter module: supports all possible baud rates, stop and parity bits, generates ready when buffer can be filled with new data.
3. New lab 11_2_note_recognition_with_filtering is a variation of lab 11 with distance value avaraging.
4. New lab 11_3_mic_to_uart is to demonstrate mic data capturing and transmitting over UART to the host. A simple hex2wav.pl perl script privided to record and convert data from serial port to .WAV file.
=> Microphone tests

docs/Beginner's-guide-to-basics-graphics-music.md
Added Beginners guide in docs branch under directory docs
=> added docs

boards/de10_lite/board_specific_top.sv
we update the management of vga for de-10 lite
=> Update way to access VGA with new configuration structure

boards/de1/board_specific_top.sv
Added Altera de1 Support to new framework
=> Added de1 Support to new framework

boards/nexys4/board_specific_top.sv
Nexys4 cosmetic changes and declared necessary signals x and y.
=> nexys4 update

boards/de1_soc/board_specific_top.sv
```
1. Add additional parameters:
parameter clk_mhz = 100,
pixel_mhz = 25,
w_key = 5,
...
w_gpio = 32,
screen_width = 640,
screen_height = 480,
w_red = 4,
w_green = 4,
w_blue = 4,
w_x = $clog2 ( screen_width ),
w_y = $clog2 ( screen_height )
..
2. Add wire declarations
wire [w_x - 1:0] x;
wire [w_y - 1:0] y;
3. Change top -> lab_top module and instance name and propagate parameters
for graphics. Remove pixel_mhz propagation if present.
lab_top
.clk_mhz ( clk_mhz ),
.w_key ( w_key ),
...
.w_gpio ( w_gpio ),
.screen_width ( screen_width ),
.screen_height ( screen_height ),
.w_red ( w_red ),
.w_green ( w_green ),
.w_blue ( w_blue )
)
i_lab_top
4. Add instance port connections
.x ( x ),
.y ( y ),
5. Remove VGA-specific signals from port connection to lab_top instance
.vsync ( Vsync ),
.hsync …
```
=> Update de1_soc according to instructions

boards/karnix_ecp5_yosys/Makefile, boards/karnix_ecp5_yosys/board_specific_top.sv, boards/orangecrab_ecp5_yosys/Makefile, boards/orangecrab_ecp5_yosys/board_specific_top.sv, labs/2_graphics/2_0_color_stripes/01_clean.bash, labs/2_graphics/2_0_color_stripes/02_simulate_rtl.bash, labs/2_graphics/2_0_color_stripes/03_synthesize_for_fpga.bash, labs/2_graphics/2_0_color_stripes/04_configure_fpga.bash, labs/2_graphics/2_0_color_stripes/05_run_gui_for_fpga_synthesis.bash, labs/2_graphics/2_0_color_stripes/06_choose_another_fpga_board.bash, labs/2_graphics/2_0_color_stripes/07_synthesize_for_asic.bash, labs/2_graphics/2_0_color_stripes/08_visualize_asic_synthesis_results_1.bash, labs/2_graphics/2_0_color_stripes/09_visualize_asic_synthesis_results_2.bash, labs/2_graphics/2_0_color_stripes/lab_top.sv, labs/2_graphics/2_0_color_stripes/tb.sv, labs/2_graphics/2_2_game/game_config.svh, labs/2_graphics/2_2_game/game_overlap.sv, labs/2_graphics/2_2_game/game_sprite_control.sv, labs/2_graphics/2_2_game/game_sprite_display.sv, labs/2_graphics/2_2_game/game_sprite_display_pipelined.sv, labs/2_graphics/2_2_game/game_sprite_top.sv, labs/2_graphics/2_2_game/game_top.sv, labs/2_graphics/2_2_game/lab_top.sv, peripherals/vga.sv, scripts/steps/00_setup_yosys.source_bash
1. Fix build issues for Karnix board.
2. Fix pixel_clk generation in vga, use pixel_clk to register output signals.
3. Fix 2_2_game lab.
4. Propose new lab: 2_0_color_stripes, useful for debugging VGA wiring.
=> New graphics: karnix build, fix vga pixel_clk, fix 2_2_game, add new lab 2_0_color_stripes

boards/eclypse_z7/board_specific.tcl, boards/eclypse_z7/board_specific.xdc, boards/eclypse_z7/board_specific_top.sv, scripts/steps/00_setup.source_bash
min version of Eclypse Z7 support
=> min version of Eclypse Z7 support

boards/eclypse_z7/board_specific.xdc, boards/eclypse_z7/board_specific_top.sv
Added TM1638 support for Eclypse Z7
=> Added TM1638 support for Eclypse Z7

boards/arty_a7_35_pmod_mic3/board_specific_top.sv
Fix wrapper (gpio port) for intance tm1638.
=> Fix tm1638 wrapper

README.md
1) OMDAZZ    -> Cyclone IV
2) RZRD          -> Cyclone IV
3) PISWORDS -> Cyclone IV + Quartus
4) SAYLINX     -> Cyclone IV + Quartus
=> fix board description for rzrd/omdazz/saylinx/piswords

labs/1_basics/1_09_hex_counter/lab_top.sv, peripherals/tm1638_registers.sv, peripherals/tm1638_using_graphics.sv
Refactoring of `r_init` in #180 for compatibility with old Quartus
Plus other refactoring for readability
=> Refactoring of r_init in #180 for compatibility with old Quartus

.github/workflows/synthesis.yml, boards/terasic_sockit/board_specific_top.sv, labs/3_music/3_0_oscilloscope/lab_top.sv, peripherals/tm1638_registers.sv, scripts/steps/00_setup_icarus.source_bash
More configs to CI
More stable board naming
Fixed tm1638_registers.sv in order to support Icarus
Fixed rtl simulation with gtkwave for 3_0 and 3_1 labs
=> Fixed simulation, enchanced CI, polishing

boards/tang_primer_20k_dock_hdmi_no_tm1638/board_specific.cst, boards/tang_primer_20k_dock_hdmi_tm1638/board_specific.cst, boards/tang_primer_20k_dock_hdmi_tm1638/board_specific_top.sv, boards/tang_primer_20k_dock_lcd_800_480_no_tm1638/board_specific.cst, boards/tang_primer_20k_dock_lcd_800_480_tm1638/board_specific.cst, boards/tang_primer_20k_dock_lcd_800_480_tm1638/board_specific_top.sv, boards/tang_primer_20k_dock_no_hdmi_no_tm1638/board_specific.cst, boards/tang_primer_20k_dock_no_hdmi_tm1638/board_specific.cst
Изменения по комментариям прошлого Pull. Убрал лишние выходы, закомментированные строки, подправил пробелы. В планах сделать tang_primer_20k_dock_lcd_800_480_tm1638_alt с Sipeed R6+1 Microphone Array Board. В LCD версии добавил в cst 5 GPIO, которые остались свободными.
=> Small changes

labs/9_events/2025_tijuana/day_1_am_combination_logic_basics/4_seven_segment_letter/hackathon_top.sv, labs/9_events/2025_tijuana/day_1_pm_graphics_using_combination_logic/2_change_color_with_keys/hackathon_top.sv, labs/9_events/2025_tijuana/day_1_pm_graphics_using_combination_logic/3_change_position_with_keys/hackathon_top.sv, labs/9_events/2025_tijuana/day_1_pm_graphics_using_combination_logic/4_ellipse_parabola_hyperbola/hackathon_top.sv, labs/9_events/2025_tijuana/day_1_pm_graphics_using_combination_logic/5_shades_of_colors/hackathon_top.sv
Homework:
- day_1_am_combination_logic_basics\4_seven_segment_letter
- day_1_pm_graphics_using_combination_logic\2_change_color_with_keys
- day_1_pm_graphics_using_combination_logic\3_change_position_with_keys
- day_1_pm_graphics_using_combination_logic\4_ellipse_parabola_hyperbola
- day_1_pm_graphics_using_combination_logic\5_shades_of_colors
=> HomeWork 1 Diego Sebastian Peralta Martinez UABC Tijuana

boards/tang_primer_20k_dock_lcd_800_480_tm1638_alt/board_specific_top.sv, labs/3_music/3_10_spectrum_analyzer/lab_top.sv, peripherals/i2s_audio_out.sv
Doubling the input signal with overload and distortion if more than the maximum volume is needed, parameter loud = 1 in module i2s_audio_out. Также добавлено корректное (с учётом отброшенных старших битов) преобразование 24 битного аудиосигнала в 11 битный в 3_10_spectrum_analyzer.
=> Maximum volume
