yuri-panchul/basics-graphics-music

scripts/asic/run_layout_viewer.mk

fix for run  08_visualize_asic_synthesis_results_1.bash and 09_visualize_asic_synthesis_results_2.bash execution  
in Ubuntu 20.0
More in:
https://github.com/The-OpenROAD-Project/OpenLane/issues/1149

OpenROAD gui fix

---

boards/de1_soc/board_specific.qsf
boards/de1_soc/board_specific.sdc
boards/de1_soc/board_specific_top.sv
scripts/steps/00_setup.source_bash

Added support for DE1 SoC (Intel, Cyclone V). Examples involving simple on-board peripherals (hex, led, key, sw, etc) are working.
Please let me know if there are any issues with change.

Added support for DE1 SoC (Intel, Cyclone V)

---

boards/c5gx/board_specific_top.sv
boards/de0/board_specific_top.sv
boards/de0_cv/board_specific_top.sv
boards/de0_nano/board_specific_top.sv
boards/de0_nano_soc/board_specific_top.sv
boards/de10_lite/board_specific_top.sv
boards/de10_lite_tm1638/board_specific_top.sv
boards/de10_nano/board_specific_top.sv
boards/de1_soc/board_specific_top.sv
boards/de2_115/board_specific_top.sv
boards/piswords6/board_specific_top.sv

c5gx, de0, de0_cv, de0_nano, de0_nano_soc, de10_lite, de10_lite_tm1638, de10_nano, de1_soc, de2_115, piswords6.

Altera boards: mic, tm1638 pins optimization

---

boards/de0_nano/board_specific_top.sv
boards/de0_nano_soc/board_specific_top.sv
boards/de10_lite_tm1638/board_specific_top.sv
boards/de10_nano/board_specific_top.sv

DE0-Nano, DE0-Nano-SoC, DE10-Lite_TM1638, DE10-Nano.

Altera boards: moved tm1638 pins close to power

---

boards/arty_a7/board_specific_top.sv
boards/c5gx/board_specific_top.sv
boards/de0/board_specific_top.sv
boards/de0_cv/board_specific_top.sv
boards/de0_nano/board_specific_top.sv
boards/de0_nano_alt_vga/board_specific_top.sv
boards/de0_nano_soc/board_specific_top.sv
boards/de10_lite/board_specific_top.sv
boards/de10_nano/board_specific_top.sv
boards/de1_soc/board_specific_top.sv
boards/de2_115/board_specific_top.sv
boards/dk_dev_3c120n/board_specific_top.sv
boards/tang_nano_20k/board_specific_top.sv
boards/tang_nano_9k/board_specific_top.sv
boards/tang_primer_20k_dock/board_specific_top.sv
boards/tang_primer_20k_dock_alt/board_specific_top.sv
boards/zybo_z7/board_specific_top.sv

In arty_a7, de0_nano, de0_nano_alt_vga, de0_nano_soc, de10_lite_tm1638, de10_nano, tang_nano_20k, tang_nano_9k, tang_primer_20k_dock, zybo_z7 wrapper with tm1638 connections rewritten.
In c5gx, de0, de0_cv, de10_lite, de1_soc, de2_115, dk_dev_3c120n only "include "config.svh"" added.
In tang_nano_20k wrapper with tm1638 connections rewritten, VGA fix.

Rewrote top wrapper all tm1638 and static 7SEG boards to config.svh

---

boards/ice40hx8k_evb_yosys/board_specific_top.sv

- fix GPIO assigment
- add ifdefs for TM1638 and INMP441, make them disabled by default
- set proper CLK for inmp441_mic_i2s_receiver module

ice40hx8k_evb_yosys: Bugfixes:

---

boards/tang_nano_9k_gowin_yosys/Makefile

'--resent' was mistakenly used while uploading to SRAM over openFPGALoader.

Remove --reset while upoading to SRAM

---

boards/ice40hx8k_evb_yosys/board_specific_top.sv
boards/orangecrab_ecp5_yosys/board_specific_top.sv

Make slow_clk signal global for ECP5 and iCE40 FPGAs by using supported by Yosys proprietary modules.

Yosys slow clk

---

boards/de0_nano_soc_vga666/board_specific_top.sv
boards/de0_nano_soc_vga_pmod/board_specific_top.sv
boards/de0_nano_vga666/board_specific_top.sv
boards/de0_nano_vga_pmod/board_specific_top.sv
boards/de10_lite_tm1638_arduino/board_specific_top.sv
boards/de10_nano_vga666/board_specific_top.sv
boards/de10_nano_vga_mister/board_specific_top.sv
boards/de10_nano_vga_pmod/board_specific_top.sv
boards/ice40hx8k_evb_yosys/board_specific_top.sv
boards/orangecrab_ecp5_yosys/board_specific_top.sv
boards/tang_nano_20k/board_specific_top.sv
boards/tang_nano_9k/board_specific_top.sv
boards/tang_nano_9k_gowin_yosys/board_specific_top.sv
boards/tang_primer_20k_dock/board_specific_top.sv
boards/tang_primer_20k_dock_alt/board_specific_top.sv
boards/tang_primer_20k_dock_gowin_yosys/board_specific_top.sv
boards/tang_primer_20k_lite/board_specific_top.sv

In many board files the tm1638_board_controller module is missing clk_mhz which causes it to produce wrong serial clock and strobe.

Pass clm_mhz to tm1638_board_controller module which was missing in a number of board files.

---

scripts/fpga/xilinx_vivado_synthesize.tcl
scripts/steps/00_setup_xilinx.source_bash

Добрый день, т.к для отображения результатов синтеза/имплементации в gui проекте Vivado, необходимо использовать project_flow с использованием runs, я решил не менять основной костяк скриптов и добавить простое создание проекта в директории run/gui_prj перед запуском non_project_flow(checkpoints), чтобы в последствии можно было открыть его скриптом .05. 
При желании пользователь может открыть чекпоинты в Vivado_GUI:
Так же пользователю придётся полностью воспроизводить все шаги до generate_bitsream в Vivado_Gui. Но сейчас в Quartus flow после запуска скрипта ./03, результаты синтеза и имплементации не видны при включении ./05 и так же приходится повторно воспроизводить все шаги.

change scripts for vivado gui

---

boards/saylinx_pmod_mic3/board_specific_top.sv

Изменение подключения PMOD MIC3:

change pin-plan for PMOD MIC3; Saylinx

---

labs/common/seven_segment_display.sv

My attempted fix consists of code from previous versions of this file + a register to store the value of the input number.
The idea is very simple: run dynamic indication on a constant high frequency, while updating the number on a much lower frequency that can be manually specified.
Has been tested on a Saylinx board.

seven_segment_display: possible refresh rate fix

---

boards/tang_nano_20k_hdmi_tm1638/board_specific.cst
boards/tang_nano_20k_hdmi_tm1638/board_specific_top.sv
boards/tang_nano_20k_lcd_800_480_tm1638/board_specific.cst
boards/tang_nano_20k_lcd_800_480_tm1638/board_specific.sdc
boards/tang_nano_20k_lcd_800_480_tm1638/board_specific_top.sv

Revised the port names according to the feedback.
Current configurations tang_nano_20k_hdmi_tm1638 and tang_nano_20k_lcd_800_480_tm1638 
are passing synthesis.
It is required to test the new version.
---
Переработал нименования портов в соответсвиие с замечаниями.
Текущие конфигурации tang_nano_20k_hdmi_tm1638 и tang_nano_20k_lcd_800_480_tm1638 
проходят синтез.
Требуется протестировать новую версию.

Refactoring pin planning for tang_nano_20k

---

boards/emooc_cc/board_specific_top.sv

Updated `VGA` and `lab_gpio` assignments for the emocc board.
Verification with the emocc board is required.

Correcting the assignment for inout ports

---

labs/3_music/3_1_note_recognizer/lab_top.sv
peripherals/inmp441_mic_i2s_receiver.sv

This commit refactors the inmp441_mic_i2s_receiver module
- A clock divisor based on a board clock frequency is used to drive SCK. This ensures inmp441 is always driven at the frequency it can support.
- A base protocol is re-implemented to better match the specification to align with both positive and negative edges of SCK.
- Basic filtering was added. Real microphones sometimes sent invalid data over the wire, these values are now filtered out and ignored.
Additionally, improve code in a note_recognizer lab to average distance over mulitple sound wave periods for increased percision. Additionally, one more exercise was added to output the actual measured frequency. This drastically simplifies debugging when clocks of the board and microphone are a bit off.

Fixes frequency detection with inmp441

---

scripts/steps/00_setup_intel_fpga.source_bash

JTAG chain depends from a board schematic, not a Cyclone V model.

bash_scripts: quartus programmer command line fix for SoCKit and de10-nano

---

.github/workflows/synthesis.yml

Github actions are enabled for Pull Requests (only, do you want for main branch?). Currently, Quartus 13 & 21 on labs 1-5 for boards 9, 35,40 are used for testing, but this is easily configurable using the following settings in the file:
```yaml
matrix:
include:
- tool: quartus
imagerepo: ghcr.io/raetro/quartus
imagever: 21.1.1
boards: 9 40
labs: 12345
```
* To add a new synthesis tool, please find a docker image and specify it as `imagerepo:` in a copy of `- tool:` entry with everything until the next section.
* To change a version of existing tool (e.g. quartus), please find it in a docker repository, e.g. https://ghcr.io/raetro/quartus, and change `imagever:`
* To change a set of board configurations to test, specify a space-separated list in `boards:`
* If you want to extend or reduce …

Introducing CI actions for testing (with Quartus currently)

---

labs/3_music/3_0_oscilloscope/lab_top.sv
peripherals/tm1638_registers.sv

Addressing comments and polishing code
Improving visualization

Oscilloscope lab polishing

---

boards/tang_nano_20k_lcd_800_480_tm1638/board_specific_top.sv
boards/tang_nano_20k_lcd_800_480_tm1638/gowin_rpll.v
boards/tang_primer_20k_dock_lcd_800_480_no_tm1638/gowin_rpll.v
boards/tang_primer_20k_dock_lcd_800_480_tm1638/board_specific_top.sv
boards/tang_primer_20k_dock_lcd_800_480_tm1638/gowin_rpll.v
peripherals/lcd_800_480.sv

Исправил ошибки в gowin_rpll.v Исправил в board_specific_top.sv значения частот pixel_mhz на правильные. Сделал 49 МГц основной частотой. Поправил пробелы и вернул закомментированным CLK в lcd_800_480.sv

Correction of clock frequency errors, assigning 49 MHz to the main frequency for Gowin Primer 20k

---

boards/de1/I2C_AUDIO_Config.v
boards/de1/I2C_Controller.v
boards/de1/I2C_WRITE_WDATA.v
boards/de1/board_specific.qsf
boards/de1/board_specific_top.sv
boards/de1_soc/I2C_AUDIO_Config.v
boards/de1_soc/I2C_Controller.v
boards/de1_soc/I2C_WRITE_WDATA.v
boards/de1_soc/board_specific_top.sv
boards/de2/I2C_AUDIO_Config.v
boards/de2/I2C_Controller.v
boards/de2/I2C_WRITE_WDATA.v
boards/de2/board_specific.qsf
boards/de2/board_specific_top.sv
boards/de2_115/I2C_AUDIO_Config.v
boards/de2_115/I2C_Controller.v
boards/de2_115/I2C_WRITE_WDATA.v
boards/de2_115/board_specific.qsf
boards/de2_115/board_specific_top.sv

de1_soc, de1, de2 and de2_115: audio output through onboard codec added.
Support for external PCM5102A has been removed.

Onboard audio codec support for Terasic boards

---

labs/3_music/3_2_melody_recognizer/lab_top.sv

It is useful to reset the state of FSM if some tones were skipped during melody recognition

Use any key to reset FSMs for melody recogintion

---

labs/5_cpu/5_3_schoolriscv_cache/01_clean.bash
labs/5_cpu/5_3_schoolriscv_cache/02_simulate_rtl.bash
labs/5_cpu/5_3_schoolriscv_cache/03_synthesize_for_fpga.bash
labs/5_cpu/5_3_schoolriscv_cache/04_configure_fpga.bash
labs/5_cpu/5_3_schoolriscv_cache/05_run_gui_for_fpga_synthesis.bash
labs/5_cpu/5_3_schoolriscv_cache/06_choose_another_fpga_board.bash
labs/5_cpu/5_3_schoolriscv_cache/07_synthesize_for_asic.bash
labs/5_cpu/5_3_schoolriscv_cache/08_visualize_asic_synthesis_results_1.bash
labs/5_cpu/5_3_schoolriscv_cache/09_visualize_asic_synthesis_results_2.bash
labs/5_cpu/5_3_schoolriscv_cache/10_run_instruction_set_simulator.bash
labs/5_cpu/5_3_schoolriscv_cache/asic_config.tcl
labs/5_cpu/5_3_schoolriscv_cache/asic_top.sv
labs/5_cpu/5_3_schoolriscv_cache/gtkwave.tcl
labs/5_cpu/5_3_schoolriscv_cache/instruction_rom.sv
labs/5_cpu/5_3_schoolriscv_cache/lab_top.sv
labs/5_cpu/5_3_schoolriscv_cache/perf_cycle_counter.sv
labs/5_cpu/5_3_schoolriscv_cache/program.s
labs/5_cpu/5_3_schoolriscv_cache/register_with_we.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_alu.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_control.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_cpu.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_cpu.svh
labs/5_cpu/5_3_schoolriscv_cache/sr_decode.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_icache.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_mem.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_register_file.sv
labs/5_cpu/5_3_schoolriscv_cache/sr_soc.sv
labs/5_cpu/5_3_schoolriscv_cache/tb.sv

This is a lab from lesson 23 of digital design school, 2024 year. The lab has been adapted for the latest version of schoolRISCV dated jul 2024.
Icarus verilog simulation supported. FPGA synthesis too.
No SDRAM support, just a slow memory imitator module.
screen_xx.png copies has been removed from all schoolRISCV cache commits.

schoolRISCV with fully associative instruction cache

---

labs/5_cpu/5_3_picorv/01_clean.bash
labs/5_cpu/5_3_picorv/02_simulate_rtl.bash
labs/5_cpu/5_3_picorv/03_synthesize_for_fpga.bash
labs/5_cpu/5_3_picorv/04_configure_fpga.bash
labs/5_cpu/5_3_picorv/05_run_gui_for_fpga_synthesis.bash
labs/5_cpu/5_3_picorv/06_choose_another_fpga_board.bash
labs/5_cpu/5_3_picorv/07_synthesize_for_asic.bash
labs/5_cpu/5_3_picorv/08_visualize_asic_synthesis_results_1.bash
labs/5_cpu/5_3_picorv/09_visualize_asic_synthesis_results_2.bash
labs/5_cpu/5_3_picorv/10_run_instruction_set_simulator.bash
labs/5_cpu/5_3_picorv/instruction_ram.sv
labs/5_cpu/5_3_picorv/lab_top.sv
labs/5_cpu/5_3_picorv/picorv32.v
labs/5_cpu/5_3_picorv/program.s
labs/5_cpu/5_3_picorv/tb.sv

> Work in progress
This is a proposal to integrate PicoRV32 core into the labs examples. 
Synthesized with Quartus Prime Lite for DE10-Lite board.
Requires checking on other boards and double checking `ram` implementation.

Add a 05_cpu lab with PicoRV32 core

---

boards/tang_nano_9k_hdmi_no_tm1638/board_specific.cst
boards/tang_nano_9k_hdmi_tm1638/board_specific.cst
boards/tang_primer_20k_dock_hdmi_no_tm1638/board_specific.cst
boards/tang_primer_20k_dock_hdmi_tm1638/board_specific.cst

On latest Gowin IDE versions (V1.9.11.03 Education) synthesis on Tang nano 4k, 9k and primer 20k with HDMI configuration results in the following error:
```
ERROR  (CT1136) : Bank 0 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'u_LVDS_clk' : IO_TYPE = LVDS25 in the same bank
ERROR  (CT1136) : Bank 0 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'u_LVDS_b' : IO_TYPE = LVDS25 in the same bank
ERROR  (CT1136) : Bank 0 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'u_LVDS_g' : IO_TYPE = LVDS25 in the same bank
ERROR  (CT1136) : Bank 0 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'gowin_add_iobuf_GPIO_1[7]' : IO_TYPE = …
```

Fix Gowin IO bank voltage conflict

---

boards/README.md

Список плат для синтеза нужно подкорректировать. Строки Orange Pi, Orange Pi MSOC, Efinix (partial support),  в картинке из Школы убрать из раздела Lattice и Orange Pi MSOC вставить в раздел Gowin.

Orange Pi MSOC transferred to Gowin

---

boards/a7_lite_35t/board_specific.tcl
boards/a7_lite_35t/board_specific.xdc
boards/a7_lite_35t/board_specific_top.sv
boards/a7_lite_35t/clk_wiz.v
boards/a7_lite_35t/clk_wiz_clk_wiz.v
peripherals/dvi_pkg.svh
peripherals/dvi_sync.sv
peripherals/dvi_top.sv
peripherals/serializer.sv
peripherals/tmds_encoder.sv
scripts/fpga/xilinx_vivado_synthesize.tcl
scripts/steps/00_setup.source_bash

Add Chinese MicroPhase [A7 Lite 35T](https://www.aliexpress.us/item/3256809647416013.html) board support.
To work with onboard HDMI [Open DVI driver](https://github.com/max-kudinov/open_dvi) is used.
Separately generated Vivado IP core is used for graphics clocking.

Add A7 Lite board support
